name: DevOps

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*"
      - "!.github/**" # Important: Exclude PRs related to .github from auto-run
      - "!.github/workflows/**" # Important: Exclude PRs related to .github/workflows from auto-run
      - "!.github/actions/**" # Important: Exclude PRs related to .github/actions from auto-run
  pull_request:
    branches: ["main"]
    paths:
      - "**/*"
      - "!.github/**" # Important: Exclude PRs related to .github from auto-run
      - "!.github/workflows/**" # Important: Exclude PRs related to .github/workflows from auto-run
      - "!.github/actions/**" # Important: Exclude PRs related to .github/actions from auto-run

permissions:
  contents: read

jobs:
  check_paths:
    uses: ./.github/workflows/check_paths.yml

  spell_check:
    needs: check_paths
    if: needs.check_paths.outputs.githubfolder != 'true' || github.event_name == 'schedule'
    uses: ./.github/workflows/spell_check.yml

  ensure_linting:
    needs:
      - check_paths
      - spell_check
    if: needs.check_paths.outputs.githubfolder != 'true' || github.event_name == 'schedule'
    uses: ./.github/workflows/ensure_linting.yml

  python_pylint:
    needs:
      - check_paths
      - spell_check
      - ensure_linting
    if: needs.check_paths.outputs.githubfolder != 'true' || github.event_name == 'schedule'
    uses: ./.github/workflows/python_pylint.yml

  python_tests:
    needs:
      - check_paths
      - spell_check
      - ensure_linting
      - python_pylint
    if: needs.check_paths.outputs.githubfolder != 'true' || github.event_name == 'schedule'
    uses: ./.github/workflows/python_tests.yml

  python_install_check:
    needs:
      - check_paths
      - spell_check
      - ensure_linting
      - python_pylint
      - python_tests
    if: needs.check_paths.outputs.githubfolder != 'true' || github.event_name == 'schedule'
    uses: ./.github/workflows/python_install_check.yml

  nix_build:
    needs:
      - check_paths
      - spell_check
      - ensure_linting
      - python_pylint
      - python_tests
      - python_install_check
    if: needs.check_paths.outputs.githubfolder != 'true' || github.event_name == 'schedule'
    uses: ./.github/workflows/nix_build.yml
